[build.environment]
  NODE_VERSION = "18"
  CI = "False"
  NPM_FLAGS = "--legacy-peer-deps"

[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps ; npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
