[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "npm install --strict-peer-deps=false --legacy-peer-deps; node_modules/.bin/vite build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
