/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[pub]': typeof import('./gun-vue/user/[pub].vue')['default']
    Blog: typeof import('./components/Blog.vue')['default']
    Chat: typeof import('./gun-vue/user/[pub]/chat.vue')['default']
    ChatGpt: typeof import('./components/ChatGpt.vue')['default']
    Diary: typeof import('./components/Diary.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    EmbedIpfs: typeof import('./components/EmbedIpfs.vue')['default']
    FormIpfs: typeof import('./components/FormIpfs.vue')['default']
    IpfsGateway: typeof import('./components/IpfsGateway.vue')['default']
    IpfsPlayer: typeof import('./components/IpfsPlayer.vue')['default']
    IpfsVideo: typeof import('./components/IpfsVideo.vue')['default']
    Keyword: typeof import('./components/Keyword.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavBottom: typeof import('./components/NavBottom.vue')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    Navier: typeof import('./components/Navier.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    NavSocial: typeof import('./components/NavSocial.vue')['default']
    Nft: typeof import('./components/Nft.vue')['default']
    NftToken: typeof import('./components/NftToken.vue')['default']
    PanelResult: typeof import('./components/VUpload/PanelResult.vue')['default']
    PanelUpload: typeof import('./components/VUpload/PanelUpload.vue')['default']
    Preferences: typeof import('./components/Preferences.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./components/VUpload/SearchResult.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    ShowInfo: typeof import('./components/ShowInfo.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Social: typeof import('./components/Social.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TokenManager: typeof import('./components/TokenManager.vue')['default']
    User: typeof import('./gun-vue/user/index.vue')['default']
    UserAvatar: typeof import('./gun-vue/user/UserAvatar.vue')['default']
    UserGraph: typeof import('./gun-vue/user/UserGraph.vue')['default']
    UserHome: typeof import('./gun-vue/user/UserHome.vue')['default']
    UserIcon: typeof import('./gun-vue/user/UserIcon.vue')['default']
    UserList: typeof import('./gun-vue/user/UserList.vue')['default']
    UserListOverlay: typeof import('./gun-vue/user/UserListOverlay.vue')['default']
    UserPanel: typeof import('./gun-vue/user/UserPanel.vue')['default']
    UserProfile: typeof import('./gun-vue/user/UserProfile.vue')['default']
    UserProfileField: typeof import('./gun-vue/user/UserProfileField.vue')['default']
    UserRooms: typeof import('./gun-vue/user/UserRooms.vue')['default']
    Users: typeof import('./gun-vue/user/users.vue')['default']
    VUpload: typeof import('./components/VUpload.vue')['default']
    Wallet: typeof import('./components/Wallet.vue')['default']
    Youtube: typeof import('./components/Youtube.vue')['default']
    YoutubePlayer: typeof import('./components/YoutubePlayer.vue')['default']
    YoutubeVideo: typeof import('./components/YoutubeVideo.vue')['default']
    YoutubeVideos: typeof import('./components/YoutubeVideos.vue')['default']
  }
}
